import { readFileSync } from 'node:fs';

const surfaces = [
  [
    'primitives',
    '../dist/index.js',
    [
      'VisuallyHidden',
      'DismissButton',
      'DIRECTORY_DRAG_TYPE',
      'DragPreview',
      'FocusRing',
      'FocusScope',
      'Focusable',
      'HiddenSelect',
      'I18nProvider',
      'ListDropTargetDelegate',
      'ListKeyboardDelegate',
      'LocalizedStringDictionary',
      'LocalizedStringFormatter',
      'ModalProvider',
      'Overlay',
      'OverlayContainer',
      'OverlayProvider',
      'Pressable',
      'RouterProvider',
      'SSRProvider',
      'UNSAFE_PortalProvider',
      'ariaHideOutside',
      'chain',
      'getTextDirection',
      'getSelection',
      'isRTL',
      'isDirectoryDropItem',
      'isFileDropItem',
      'isTextDropItem',
      'mergeProps',
      'mergeRefs',
      'setTokenFieldSelection',
      'tokenFieldPositionToDOMRange',
      'useButton',
      'useBreadcrumbItem',
      'useBreadcrumbs',
      'useCheckbox',
      'useCheckboxGroup',
      'useCheckboxGroupItem',
      'useCollator',
      'useClipboard',
      'useComboBox',
      'useContextMenu',
      'useDateFormatter',
      'useDisclosure',
      'useDialog',
      'useDrag',
      'useDraggableCollection',
      'useDraggableItem',
      'useDrop',
      'useDropIndicator',
      'useDroppableCollection',
      'useDroppableItem',
      'useField',
      'useFocus',
      'useFocusable',
      'useFocusManager',
      'useFocusRing',
      'useFocusVisible',
      'useFocusWithin',
      'useGridList',
      'useGridListItem',
      'useGridListSection',
      'useGridListSelectionCheckbox',
      'useFilter',
      'useHover',
      'useHiddenSelect',
      'useInteractOutside',
      'useIsSSR',
      'useKeyboard',
      'useLink',
      'useListBox',
      'useListBoxSection',
      'useListFormatter',
      'useLocalizedStringDictionary',
      'useLocalizedStringFormatter',
      'useLongPress',
      'useLandmark',
      'useLocale',
      'useLabel',
      'useMenu',
      'useMenuItem',
      'useMenuSection',
      'useMenuTrigger',
      'useMeter',
      'useModal',
      'useModalProvider',
      'useModalOverlay',
      'useMove',
      'useNumberFormatter',
      'useNumberField',
      'useObjectRef',
      'useOverlay',
      'useOverlayPosition',
      'useOverlayTrigger',
      'useOption',
      'usePopover',
      'usePress',
      'usePreventScroll',
      'usePreviewTrigger',
      'useProgressBar',
      'useRadio',
      'useRadioGroup',
      'useSearchField',
      'useSelect',
      'useSeparator',
      'useSlider',
      'useSliderThumb',
      'useSwitch',
      'useSubmenuTrigger',
      'useTab',
      'useTabList',
      'useTabPanel',
      'useTag',
      'useTagGroup',
      'useTable',
      'useTableCell',
      'useTableColumnHeader',
      'useTableColumnResize',
      'useTableHeaderRow',
      'useTableRow',
      'useTableRowGroup',
      'useTableSelectAllCheckbox',
      'useTableSelectionCheckbox',
      'useTextField',
      'useToggleButton',
      'useToggleButtonGroup',
      'useToggleButtonGroupItem',
      'useToolbar',
      'useToast',
      'useToastRegion',
      'useToken',
      'useTokenField',
      'useTooltip',
      'useTooltipTrigger',
      'useTree',
      'useTreeItem',
      'useId',
      'useVisuallyHidden',
      'useUNSAFE_PortalContext',
      'UNSTABLE_createLandmarkController',
    ],
  ],
  [
    'components',
    '../dist/components.js',
    [
      'Button',
      'Breadcrumb',
      'Breadcrumbs',
      'Checkbox',
      'CheckboxGroup',
      'CheckboxGroupItem',
      'ComboBox',
      'ComboBoxItem',
      'Disclosure',
      'Dialog',
      'GridList',
      'GridListItem',
      'GridListSection',
      'GridListSelectionCheckbox',
      'Link',
      'ListBox',
      'Menu',
      'MenuItem',
      'MenuTrigger',
      'Meter',
      'Modal',
      'NumberField',
      'Option',
      'Popover',
      'ProgressBar',
      'Radio',
      'RadioGroup',
      'SearchField',
      'Select',
      'SelectItem',
      'Separator',
      'Slider',
      'Switch',
      'Tab',
      'TabList',
      'TabPanel',
      'Tabs',
      'Tag',
      'TagGroup',
      'Table',
      'TableBody',
      'TableCell',
      'TableColumn',
      'TableColumnResizer',
      'TableHeader',
      'TableRow',
      'TableSelectAllCheckbox',
      'TableSelectionCheckbox',
      'TextField',
      'ToggleButton',
      'ToggleButtonGroup',
      'ToggleButtonGroupItem',
      'Toolbar',
      'Toast',
      'ToastRegion',
      'Tooltip',
      'Tree',
      'TreeItem',
      'VisuallyHidden',
    ],
  ],
];

const failures = await Promise.all(
  surfaces.map(async ([label, moduleId, expected]) => {
    const module = await import(moduleId);
    const missing = expected.filter((name) => !(name in module));
    if (missing.length) console.error(`${label}: missing ${missing.join(', ')}`);
    else console.log(`${label}: ${expected.length} native exports verified`);
    return missing.length > 0;
  }),
);

if (failures.some(Boolean)) process.exitCode = 1;

const baseline = JSON.parse(
  readFileSync(new URL('../docs/react-aria-3.51.0-runtime-exports.json', import.meta.url), 'utf8'),
);
const primitives = await import('../dist/index.js');
const directMatches = baseline.exports.filter((name) => name in primitives);
const remaining = baseline.exports.filter((name) => !(name in primitives));
const nativeExtensions = Object.keys(primitives).filter((name) => !baseline.exports.includes(name));

console.log(
  `upstream: ${directMatches.length}/${baseline.exports.length} direct runtime names matched against react-aria@${baseline.version}`,
);
console.log(
  `upstream: ${remaining.length} direct names remain; behavior-level mappings are tracked by family`,
);
console.log(
  `native: ${nativeExtensions.length} Preact-specific exports (${nativeExtensions.join(', ')})`,
);
